services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lnu_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - lnu_net

  web:
    image: nginx:alpine
    container_name: lnu_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lnu_net

  db:
    image: mysql:8.0
    container_name: lnu_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: lnu_marketplace
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - lnu_db_data:/var/lib/mysql
    networks:
      - lnu_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lnu_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lnu_net


networks:
  lnu_net:

volumes:
  lnu_db_data:
