services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: lnu_app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - lnu_net

  web:
    image: nginx:alpine
    container_name: lnu_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - lnu_net

  db:
    image: mariadb:11
    container_name: lnu_db
    environment:
      MARIADB_DATABASE: lnu_marketplace
      MARIADB_USER: lnu_user
      MARIADB_PASSWORD: lnu_pass
      MARIADB_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - lnu_db_data:/var/lib/mysql
    networks:
      - lnu_net

networks:
  lnu_net:

volumes:
  lnu_db_data: